name: Build TPD Tracker

on:
  push:
  workflow_dispatch:   # позволяет запустить вручную с кнопки на GitHub

jobs:
  build:
    name: Build .geode file
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build mod (Geode SDK автоматически скачается)
        uses: geode-sdk/build-geode-mod@main
        id: build

      - name: Upload .geode file
        uses: actions/upload-artifact@v4
        with:
          name: TPDTracker
          path: ${{ steps.build.outputs.build-output }}
